on:
  push:
    branches: master

name: blogdown

jobs:
  build:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      TARGET_BRANCH: gh-pages
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup R
        uses: r-lib/actions/setup-r@master

      - name: Install pandoc and pandoc citeproc
        run: |
          brew install pandoc
          brew install pandoc-citeproc

      - name: Cache Renv packages
        uses: actions/cache@v1
        with:
          path: $HOME/.local/share/renv
          key: r-${{ hashFiles('renv.lock') }}
          restore-keys: r-

      - name: Install packages
        run: |
          R -e 'install.packages("renv")'
          R -e 'renv::restore()'

      - name: Install hugo
        run: |
          R -e 'blogdown::install_hugo()'

      - name: Build site
        run: |
          R -e 'blogdown::build_site()'

      - name: Configure Git
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          
      - name: Clone existing gh-pages branch
        run: |
          mkdir -p $HOME/site
          cp -Rf public/ $HOME/site
          cd $HOME
          git clone --quiet --branch=$TARGET_BRANCH https://${GITHUB_PAT}@github.com/${GITHUB_REPOSITORY}.git $TARGET_BRANCH
          cp -R $TARGET_BRANCH/.git $HOME/.git
          rm -rf $TARGET_BRANCH/*
          cp -R $HOME/.git $TARGET_BRANCH/.git
          cd $TARGET_BRANCH
          cp -Rf $HOME/site .
          git add -Af .
          git commit -m "Built site for $GITHUB_REPOSITORY"
          git push -fq origin $TARGET_BRANCH
